### ISSUE TITLE
Відсутні наступні сервіси, для роботи з відео

### ISSUE THREAD

**Issue by putsan** [nikit0ns/awesome-artificial-intelligence#1]
Я б додав їх  в сам документ, але не впевнений у які категорії..

1. [invideo.io](invideo.io) — для генерації відео
2. [captions.ai](captions.ai)  — автоматичне створення якісних субтитрів і не тільки це!

**Comment by putsan** [comment]
Можливо пізніше я сам закрию це Іш'ю [згідно рекомендацій](https://github.com/nikit0ns/artificial-intelligence-library/blob/master/CONTRIBUTING.md), а поки не маю достатньо часу..

Та й нагода для новачків попрактикуватися буде)

**Comment by nikit0ns** [comment]
Thank you, all added.
